version: "3.9"

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: test_db
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_password
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./tests/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  backend:
    build: ./backend
    env_file: .env
    depends_on:
      - db
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    env_file: .env
    depends_on:
      - backend
    ports:
      - "8501:8501"

volumes:
  db_data:
